language: elixir

elixir:
  - 1.8.1
  - 1.9.1

otp_release:
  - 21.2
  - 22.0

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix format --check-formatted
  - mix coveralls.travis
  - mix credo

branches:
  only:
    - master
    - bug-fix
