on: push

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [21.3.8.10, 22.2]
        elixir: [1.8.2, 1.9.4, 1.10.0]
        exclude:
          - {otp: "21.3.8.10", elixir: "1.10.0"}

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        id: cache-mix-deps
        with:
          path: deps
          key: ${{matrix.otp}}-${{matrix.elixir}}-mix-${{hashFiles(format('{0}{1}', github.workspace, '/mix.exs'))}}-${{hashFiles(format('{0}{1}', github.workspace, '/mix.lock'))}}
          restore-keys: |
            ${{matrix.otp}}-${{matrix.elixir}}-mix-
      - run: mix deps.get
        if: steps.cache-mix-deps.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.cache-mix-deps.outputs.cache-hit != 'true'
      - run: XGIT_FORCE_COVERAGE=1 mix coveralls.json
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
